### ISSUE TITLE
Force drop the www in the url

### ISSUE THREAD

**Issue by PuttItOut** [IcyDefiance/Veuwer#12]
The use of WWW isn't as pretty as a stripped one. 

http://veuwer.com/ - GOOD
http://www.veuwer.com - NOT AS GOOD

**Comment by IcyDefiance** [comment]
Good idea. Not sure how well I can control the address bar, but the links given next to each image are easy to change. Expect this in the next update I push.

**Comment by PuttItOut** [comment]
I can help you out if needed. You can use an IHttpModule to intercept events or a <urlRewrite> rule in the web.config. 

I'd suggest in the meantime that you format all links without the www. Currently your pages have www in all display links.

http://veuwer.com/9

Good job btw on this project.

**Comment by IcyDefiance** [comment]
Yep, that was easier than expected. And thanks. :)
