### ISSUE TITLE
Submit galley to voat link is broken

### ISSUE THREAD

**Issue by thomasmcgannon** [IcyDefiance/Veuwer#14]
The link has the following url:

https://voat.co/submit?linkpost=true&url=http://veuwer.com/http://veuwer.com/{...,...}

As you can see it has **http://veuwer.com** twice, leading to a broken URL been generated.

**Comment by IcyDefiance** [comment]
Whoops, you're right. Thanks for mentioning it. I can probably push a fix in a few minutes...
